
title: WHANet
page-top-title: WHANet
top-section-bg-text: 'WHANet： Wavelet and Hybrid Attention Network for  OCTA Vessel Segmentation'
home-subtitle: Datatset Description
copyright-text: '&copy; Units: Qufu Normal University Computer College. Email: mafei0603@163.com.'
